- CONFIG_ARM_HIKEY_OUTSTANDING_PREFETCHERS: 0
- CONFIG_ARM_HIKEY_PREFETCHER_STRIDE: 0
- CONFIG_ARM_HIKEY_PREFETCHER_NPFSTRM: 0
- CONFIG_ARM_HIKEY_PREFETCHER_STBPFDIS: false
- CONFIG_ARM_HIKEY_PREFETCHER_STBPFRS: false
- CONFIG_PLAT_IMX7: false
- CONFIG_USER_TOP: '0xa0000000'
- CONFIG_ARCH_AARCH32: false
- CONFIG_ARCH_AARCH64: true
- CONFIG_ARCH_ARM_HYP: false
- CONFIG_ARCH_RISCV32: false
- CONFIG_ARCH_RISCV64: false
- CONFIG_ARCH_X86_64: false
- CONFIG_ARCH_IA32: false
- CONFIG_SEL4_ARCH: aarch64
- CONFIG_ARCH_ARM: false
- CONFIG_ARCH: arm
- CONFIG_ARCH_ARM: true
- CONFIG_WORD_SIZE: 64
- CONFIG_ARM_PLAT: tx2
- CONFIG_MACH: nvidia
- CONFIG_PLAT_BCM2711: false
- CONFIG_PLAT_BCM2837: false
- CONFIG_PLAT_FVP: false
- CONFIG_PLAT_HIKEY: false
- CONFIG_PLAT_IMX8MQ_EVK: false
- CONFIG_PLAT_IMX8MM_EVK: false
- CONFIG_PLAT_MAAXBOARD: false
- CONFIG_PLAT_ODROIDC2: false
- CONFIG_PLAT_ODROIDC4: false
- CONFIG_PLAT_QEMU_ARM_VIRT: false
- CONFIG_PLAT_QUARTZ64: false
- CONFIG_PLAT_ROCKPRO64: false
- CONFIG_PLAT_TQMA8XQP1GB: false
- CONFIG_PLAT_TX1: false
- CONFIG_PLAT_TX2: true
- CONFIG_PLAT_ZYNQMP: false
- CONFIG_PLAT: tx2
- CONFIG_ARM_CORTEX_A7: false
- CONFIG_ARM_CORTEX_A8: false
- CONFIG_ARM_CORTEX_A9: false
- CONFIG_ARM_CORTEX_A15: false
- CONFIG_ARM_CORTEX_A35: false
- CONFIG_ARM_CORTEX_A53: false
- CONFIG_ARM_CORTEX_A55: false
- CONFIG_ARM_CORTEX_A57: true
- CONFIG_ARM_CORTEX_A72: false
- CONFIG_ARCH_ARM_V7A: false
- CONFIG_ARCH_ARM_V7VE: false
- CONFIG_ARCH_ARM_V8A: true
- CONFIG_ARM_SMMU: false
- CONFIG_AARCH64_SERROR_IGNORE: true
- CONFIG_ARM_MACH: nvidia
- CONFIG_KERNEL_MCS: true
- CONFIG_ARM_PA_SIZE_BITS_40: false
- CONFIG_ARM_PA_SIZE_BITS_44: true
- CONFIG_ARM_ICACHE_VIPT: ''
- CONFIG_DEBUG_DISABLE_L2_CACHE: false
- CONFIG_DEBUG_DISABLE_L1_ICACHE: false
- CONFIG_DEBUG_DISABLE_L1_DCACHE: false
- CONFIG_DEBUG_DISABLE_BRANCH_PREDICTION: false
- CONFIG_ARM_HYPERVISOR_SUPPORT: false
- CONFIG_ARM_GIC_V3_SUPPORT: false
- CONFIG_AARCH64_VSPACE_S2_START_L1: false
- CONFIG_ARM_HYP_ENABLE_VCPU_CP14_SAVE_AND_RESTORE: false
- CONFIG_ARM_ERRATA_430973: false
- CONFIG_ARM_ERRATA_773022: false
- CONFIG_ARM_SMMU: false
- CONFIG_TK1_SMMU: false
- CONFIG_ENABLE_A9_PREFETCHER: false
- CONFIG_EXPORT_PMU_USER: true
- CONFIG_DISABLE_WFI_WFE_TRAPS: false
- CONFIG_SMMU_INTERRUPT_ENABLE: false
- CONFIG_AARCH32_FPU_ENABLE_CONTEXT_SWITCH: false
- CONFIG_AARCH64_SERROR_IGNORE: true
- CONFIG_L1_CACHE_LINE_SIZE_BITS: 6
- CONFIG_EXPORT_PCNT_USER: false
- CONFIG_EXPORT_VCNT_USER: false
- CONFIG_EXPORT_PTMR_USER: false
- CONFIG_EXPORT_VTMR_USER: false
- CONFIG_VTIMER_UPDATE_VOFFSET: true
- CONFIG_HAVE_FPU: true
- CONFIG_PADDR_USER_DEVICE_TOP: 17592186044416
- CONFIG_ROOT_CNODE_SIZE_BITS: 12
- CONFIG_BOOT_THREAD_TIME_SLICE: 5
- CONFIG_RETYPE_FAN_OUT_LIMIT: 256
- CONFIG_MAX_NUM_WORK_UNITS_PER_PREEMPTION: 100
- CONFIG_RESET_CHUNK_BITS: 8
- CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS: 230
- CONFIG_FASTPATH: true
- CONFIG_NUM_DOMAINS: 1
- CONFIG_SIGNAL_FASTPATH: true
- CONFIG_NUM_PRIORITIES: 256
- CONFIG_MAX_NUM_NODES: 1
- CONFIG_ENABLE_SMP_SUPPORT: false
- CONFIG_KERNEL_STACK_BITS: 12
- CONFIG_FPU_MAX_RESTORES_SINCE_SWITCH: 64
- CONFIG_VERIFICATION_BUILD: false
- CONFIG_BINARY_VERIFICATION_BUILD: false
- CONFIG_DEBUG_BUILD: false
- CONFIG_HARDWARE_DEBUG_API: false
- CONFIG_PRINTING: false
- CONFIG_KERNEL_INVOCATION_REPORT_ERROR_IPC: false
- CONFIG_NO_BENCHMARKS: false
- CONFIG_BENCHMARK_GENERIC: false
- CONFIG_BENCHMARK_TRACK_KERNEL_ENTRIES: false
- CONFIG_BENCHMARK_TRACEPOINTS: false
- CONFIG_BENCHMARK_TRACK_UTILISATION: true
- CONFIG_KERNEL_BENCHMARK: track_utilisation
- CONFIG_ENABLE_BENCHMARKS: true
- CONFIG_KERNEL_LOG_BUFFER: false
- CONFIG_MAX_NUM_TRACE_POINTS: 0
- CONFIG_IRQ_REPORTING: false
- CONFIG_COLOUR_PRINTING: false
- CONFIG_USER_STACK_TRACE_LENGTH: 0
- CONFIG_KERNEL_OPT_LEVEL_O2: false
- CONFIG_KERNEL_OPT_LEVEL_OS: false
- CONFIG_KERNEL_OPT_LEVEL_O0: false
- CONFIG_KERNEL_OPT_LEVEL_O1: false
- CONFIG_KERNEL_OPT_LEVEL_O3: false
- CONFIG_KERNEL_OPT_LEVEL: -O2
- CONFIG_KERNEL_OPT_LEVEL_O2: true
- CONFIG_KERNEL_OPTIMISATION_CLONE_FUNCTIONS: true
- CONFIG_KERNEL_FWHOLE_PROGRAM: false
- CONFIG_DANGEROUS_CODE_INJECTION: false
- CONFIG_DEBUG_DISABLE_PREFETCHERS: false
- CONFIG_SET_TLS_BASE_SELF: false
- CONFIG_KERNEL_WCET_SCALE: 1
- CONFIG_KERNEL_STATIC_MAX_PERIOD_US: 0
- CONFIG_CLZ_32: false
- CONFIG_CLZ_64: false
- CONFIG_CTZ_32: false
- CONFIG_CTZ_64: false
- CONFIG_CLZ_NO_BUILTIN: false
- CONFIG_CTZ_NO_BUILTIN: false
